config/routes.rb
Rails.application.routes.draw do

  resources :patients, only: [:index] do
    resources :plan_of_cares, only: [:index, :show, :new, :create]
    resources :comments, only: [:new, :create]
    resources :pronunciations, only: [:new, :create]
  end

  resources :goals do
    resources :sub_goals, except: [:index, :show] do
      resources :words, except: [:index, :show]
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "patients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :patient
  belongs_to :sub_goal
end

app/models/goal.rb
class Goal < ApplicationRecord
  has_many :sub_goals, dependent: :destroy

  has_many :plan_of_cares
  has_many :patients, through: :plan_of_cares

  validates :title, presence: true, uniqueness: true

  scope :alphabetically, -> { order('title') }
  scope :ltg, -> { where(goal_type: 'LTG') }
  scope :stg, -> { where(goal_type: 'STG') }
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :plan_of_cares
  has_many :goals, through: :plan_of_cares

  has_many :comments
  has_many :sub_goals, through: :comments

  has_many :pronunciations
  has_many :words, through: :pronunciations
end

app/models/plan_of_care.rb
class PlanOfCare < ApplicationRecord
  belongs_to :patient
  belongs_to :goal
end

app/models/pronunciation.rb
class Pronunciation < ApplicationRecord
  belongs_to :patient
  belongs_to :word
end

app/models/sub_goal.rb
class SubGoal < ApplicationRecord
  belongs_to :goal
  has_many :words, dependent: :destroy

  has_many :comments
  has_many :patients, through: :comments

  validates :title, presence: true, uniqueness: { scope: :goal_id }
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :sub_goal

  has_many :pronunciations
  has_many :patients, through: :pronunciations

  validates :name, presence: true, uniqueness: { scope: :sub_goal_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_patient

  def new
    @sub_goal = SubGoal.find(params[:sub_goal_id])
    @comment = @patient.comments.build
  end

  def create
    @comment = @patient.comments.build(comment_params)

    if @comment.save
      redirect_to patient_plan_of_care_path(@patient, @comment.sub_goal.goal), notice: 'Comment registered'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def find_patient
    @patient = Patient.find(params[:patient_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:patient_id, :sub_goal_id, :message)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: %i[edit update destroy]

  def index
    @goals = Goal.alphabetically
    @ltg_goals = @goals.ltg
    @stg_goals = @goals.stg
  end

  def show
    @goal = Goal.includes(sub_goals: :words).find(params[:id])
  end

  def new
    @goal = Goal.new
  end

  def edit; end

  def create
    @goal = Goal.new(goal_params)

    if @goal.save
      redirect_to goals_path, notice: 'Goal was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @goal.update(goal_params)
      redirect_to goal_path(@goal), notice: "'#{@goal.title}' updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @goal.destroy
    redirect_to goals_path, notice: 'Goal was successfully destroyed.'
  end

  private

  def set_goal
    @goal = Goal.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:title, :goal_type, :more_info)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end
end

app/controllers/plan_of_cares_controller.rb
class PlanOfCaresController < ApplicationController
  before_action :find_patient
  before_action :find_patient_goal, only: %i[index new]

  def index
    @patient_ltg_goals = @patient_goals.ltg
    @patient_stg_goals = @patient_goals.stg
  end

  def show
    @goal = Goal.includes(sub_goals: :words).find(params[:id])
  end

  def new
    @poc = @patient.plan_of_cares.build
    @available_goals = Goal.where.not(id: @patient_goals.pluck(:id)).alphabetically
  end

  def create
    @poc = @patient.plan_of_cares.build(plan_of_cares_params)

    if @poc.save
      redirect_to patient_plan_of_cares_path(@patient), notice: 'New plan added.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def find_patient
    @patient = Patient.find(params[:patient_id])
  end

  def find_patient_goal
    @patient_goals = @patient.goals.alphabetically
  end

  def plan_of_cares_params
    params.require(:plan_of_care).permit(:patient_id, :goal_id)
  end
end

app/controllers/sub_goals_controller.rb
class SubGoalsController < ApplicationController
  before_action :set_sub_goal, only: %i[edit update destroy]

  before_action :set_goal

  def new
    @sub_goal = @goal.sub_goals.build
  end

  def edit; end

  def create
    @sub_goal = @goal.sub_goals.build(sub_goal_params)

    if @sub_goal.save
      redirect_to goal_path(@goal), notice: 'Sub goal was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @sub_goal.update(sub_goal_params)
      redirect_to goal_path(@goal), notice: 'Sub goal was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @sub_goal.destroy
    redirect_to goal_path(@goal), notice: 'Sub goal was successfully destroyed.'
  end

  private

  def set_goal
    @goal = Goal.find(params[:goal_id])
  end

  def set_sub_goal
    @sub_goal = SubGoal.find(params[:id])
  end

  def sub_goal_params
    params.require(:sub_goal).permit(:title, :goal_id)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: %i[edit update destroy]
  before_action :find_goal
  before_action :find_sub_goal

  def new
    @word = @sub_goal.words.build
  end

  def edit; end

  def create
    @word = @sub_goal.words.build(word_params)

    if @word.save
      redirect_to goal_path(@goal), notice: "Word created: #{@word.name}"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @word.update(word_params)
      redirect_to goal_path(@goal), notice: 'Word was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @word.destroy
    redirect_to goal_path(@goal), notice: "'#{@word.name}' deleted"
  end

  private

  def find_goal
    @goal = Goal.find(params[:goal_id])
  end

  def find_sub_goal
    @sub_goal = SubGoal.includes(:words).find(params[:sub_goal_id])
  end

  def set_word
    @word = Word.find(params[:id])
  end

  def word_params
    params.require(:word).permit(:name, :sub_goal_id, :word_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render(partial: 'application/error_messages', locals: { object: object })
  end

  def notification(type, color)
    "<div class='notification-#{color}'>#{type}</div>".html_safe if type.present?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/plan_of_cares_helper.rb
module PlanOfCaresHelper
end

app/helpers/pronunciations_helper.rb
module PronunciationsHelper
end

app/helpers/sub_goals_helper.rb
module SubGoalsHelper
end

app/helpers/words_helper.rb
module WordsHelper
  def calc_score(patient, word)
    trials = patient.pronunciations.find_by(word_id: word.id).trials
    success = trials.count('+')
    total = trials.length
    ["#{success}/#{total}", (success * 100) / total]
  end

  def prompting_level(patient, word)
    level = patient.pronunciations.find_by(word_id: word.id).prompting_level

    case level
    when 'Independent'
      "<div class='independent'>Independent</div>".html_safe
    when 'Intermediate'
      "<div class='intermediate'>Intermediate</div>".html_safe
    else
      "<div class='controlling'>Controlling</div>".html_safe
    end
  end
end

app/views/comments/_form.html.erb
<%= form_with(model: [@patient, @comment], local: true) do |form| %>

  <%=error_messages_for(form.object) %>

  <div class="my-form__info">
    <div>
      <span>Goal:</span>
      <%= @sub_goal.goal.title %>
    </div>
    <div>
      <span>Sub-Goal:</span>
      <%= @sub_goal.title %>
    </div>
  </div>

  <%= form.hidden_field :patient_id %>
  <%= form.hidden_field :sub_goal_id, value: @sub_goal.id %>

  <div class="my-form__control">
    <%= form.label :message%>
    <%= form.text_area :message, placeholder: "How did #{@patient.name} performed in achieving sub-goal: #{@sub_goal.title}?" %>
  </div>

  <div class="my-form__control">
    <%= form.submit class: 'my-form__action-btn' %>
  </div>
<% end %>

app/views/comments/new.html.erb
<% @page_title = "Comment on #{@patient.name}'s Performance" %>

<div class="my-form">
  <%= link_to "<< Go Back", patient_plan_of_care_path(@patient, @sub_goal.goal) %>
  <div class="my-form__body">
    <%= render "form" %>
  </div>
</div>

app/views/goals/_form.html.erb
<%= form_with(model: goal) do |form| %>

  <%=error_messages_for(form.object) %>

  <div class="my-form__control">
    <%= form.label :title, 'Title of the Goal:' %>
    <%= form.text_field :title, placeholder: 'e.g. named vocabulary in pictures -visual/verbal/max cues' %>
  </div>

  <div class="my-form__control">
    <%= form.label :goal_type, 'Goal Type:' %>
    <%= form.select :goal_type, %w[LTG STG] %>
  </div>

  <div class="my-form__control">
    <%= form.label :more_info, 'More Information(optional):' %>
    <%= form.text_area :more_info, placeholder: 'e.g. Expressive/Pragmatic Language - book (the tiny seed)' %>
  </div>

  <div class="my-form__control">
    <%= form.submit class: 'my-form__action-btn' %>
  </div>
<% end %>

app/views/goals/_goal.html.erb
<div class="show_container d-flex">
  <div class="show__left">
    <div>
      <% if @patient %>
        <%= link_to "<< Go Back", patient_plan_of_cares_path(@patient), class: 'back__link' %>
      <% else %>
        <%= link_to "<< Go Back", goals_path, class: 'back__link' %>
      <% end %>
    </div>
    <%= render 'layouts/notifications' %>
    <div class="d-flex flex-column align-items-center px-4 goal__body">
      <div class="goal__type my-2"><%= goal.goal_type === 'STG' ? 'Short Term Goal' : 'Long term Goal' %></div>
      <div class="goal__title my-2"><%= goal.title %></div>
      <div class="goal__info my-2"><%= goal.more_info %></div>
    </div>
    <div class="d-flex justify-content-between my-button-group">
      <% if @patient.nil? %>
        <%= button_to "Delete", goal, method: :delete, class: 'my-btn my-btn__delete' %>
        <%= link_to "Edit", edit_goal_path(goal), class: 'my-btn' %>
        <%= link_to "Add sub-goal", new_goal_sub_goal_path(goal), class: 'my-btn' %>
      <% end %>
    </div>
  </div>
  <div class="show__right">
    <div class="accordion accordion-flush" id="accordionFlushExample">

      <% if goal.sub_goals.size.zero? %>
        <div class="no_content__message">
          No sub-goals available
          <span>You have the opportunity to ADD the very first sub-goal :)</span>
        </div>
      <% else %>
        <% goal.sub_goals.each do |sub_goal| %>
          <%= render sub_goal, goal: goal, role: role %>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/goals/edit.html.erb
<% @page_title = truncate("Edit | #{@goal.title}", length: 50) %>

<div class="my-form">
  <%= link_to "<< Go Back", goal_path(@goal), class: 'back__link' %>
  <div class="my-form__body">
    <%= render "form", goal: @goal %>
  </div>
</div>

app/views/goals/index.html.erb
<% @page_title = 'All Goals' %>

<div class="d-flex justify-content-between">
  <%= render 'layouts/notifications' %>
  <%= link_to "Add New goal", new_goal_path, class: 'my-btn' %>
</div>

<% if @goals.size.zero? %>
  <div class="no_content__message">
    No goals available
    <span>You have the opportunity to ADD the very first goal :)</span>
  </div>
<% end %>


<div class="d-flex mt-1 goals">
  <div class="goals__item">
    <% @ltg_goals.each do |goal| %>
      <div class="my-tile my-tile__ltg">
        <%= link_to goal_path(goal.id), class: 'my-tile__item' do %>
          <div class="goal-type"><%= goal.goal_type %></div>
          <div class="goal-title"><%= truncate(goal.title, length: 70) %></div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="goals__item">
    <% @stg_goals.each do |goal| %>
      <div class="my-tile my-tile__stg">
        <%= link_to goal_path(goal.id), class: 'my-tile__item' do %>
          <div class="goal-type"><%= goal.goal_type %></div>
          <div class="goal-title"><%= goal.title %></div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/goals/new.html.erb
<% @page_title = 'Add New Goal' %>

<div class="my-form">
  <%= link_to "<< Go Back", goals_path, class: 'back__link' %>
  <div class="my-form__body">
    <%= render "form", goal: @goal %>
  </div>
</div>

app/views/goals/show.html.erb
<% @page_title = truncate(@goal.title, length: 50) %>

<%= render @goal, role: 'admin'%>

app/views/patients/index.html.erb
<% @page_title = 'All Patients' %>

<div class="patients">
  <% @patients.each do |patient| %>
    <div class="patient">
      <%= link_to patient.name, patient_plan_of_cares_path(patient) %>
    </div>
  <% end %>
</div>

app/views/plan_of_cares/_form.html.erb
<%= form_with(model: [@patient, @poc], local: true) do |form| %>

  <%=error_messages_for(form.object) %>

  <div class="my-form__info">
    <%= form.label :goal_id, "Select a goal for #{@patient.name}" %>
    <%= form.select(:goal_id, @available_goals.map { |g| ["#{g.goal_type} | #{g.title}", g.id] }) %>
  </div>

  <div class="my-form__info">
    <%= form.submit class: 'my-form__action-btn' %>
  </div>
<% end %>

app/views/plan_of_cares/index.html.erb
<% @page_title = "#{@patient.name}'s Plan of Care" %>

<div class="d-flex justify-content-between">
  <%= link_to '<< Go Back', root_path, class: 'back__link ' %>
  <%= link_to "Assign new goal to #{@patient.name}", new_patient_plan_of_care_path(@patient), class: 'my-btn' %>
</div>


<% if @patient_goals.size.zero? %>
  <div class="no_content__message">
    No goals available
    <span>Assign new goals to <%= @patient.name %> :)</span>
  </div>
<% end %>


<div class="d-flex mt-1 goals">
  <div class="goals__item">
    <% @patient_ltg_goals.each do |goal| %>
      <div class="my-tile my-tile__ltg">
        <%= link_to patient_plan_of_care_path(@patient, goal), class: 'my-tile__item' do %>
          <div class="goal-type"><%= goal.goal_type %></div>
          <div class="goal-title"><%= truncate(goal.title, length: 70) %></div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="goals__item">
    <% @patient_stg_goals.each do |goal| %>
      <div class="my-tile my-tile__stg">
        <%= link_to patient_plan_of_care_path(@patient, goal), class: 'my-tile__item' do %>
          <div class="goal-type"><%= goal.goal_type %></div>
          <div class="goal-title"><%= truncate(goal.title, length: 70) %></div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>



<%# @patient_goals.each do |goal| %>
<%#= render goal, role: 'therapist' %>
<%# end %>

app/views/plan_of_cares/new.html.erb
<% @page_title = "Add New Goal for #{@patient.name}" %>

<div class="my-form">
  <%= link_to "<< Go Back", patient_plan_of_cares_path(@patient) %>
  <div class="my-form__body">
    <%= render "form" %>
  </div>
</div>

app/views/plan_of_cares/show.html.erb
<% @page_title = "#{@patient.name}'s Plan of Care" %>

<%= render @goal, role: 'therapist' %>

app/views/sub_goals/_form.html.erb
<%= form_with(model: [@goal, sub_goal], local: true) do |form| %>

  <%=error_messages_for(form.object) %>

  <div class="my-form__info">
    <span>Goal:</span>
    <%= @goal.title %>
  </div>

  <div class="my-form__control">
    <%= form.label :title, 'Title of the Sub-Goal:' %>
    <%= form.text_field :title, placeholder: 'e.g. /sh/ IWP imitative' %>
  </div>

  <div class="my-form__control">
    <%= form.submit class: 'my-form__action-btn' %>
  </div>
<% end %>

app/views/sub_goals/_sub_goal.html.erb
<div class="accordion-item">
  <h2 class="accordion-header" id="flush-headingOne">
    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-<%= sub_goal.id %>" aria-expanded="false" aria-controls="flush-<%= sub_goal.id %>">
      <%= sub_goal.title %>
    </button>
  </h2>
  <div id="flush-<%= sub_goal.id %>" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample" >
    <div class="accordion-body">
      <div class="card">
        <% sub_goal.words.each do |word| %>
          <%= render word, goal: goal, sub_goal: sub_goal, role: role %>
        <% end %>
      </div>
      <div class="acc-body__controls">
        <% if @patient.nil? %>
          <%= link_to "Add word", new_goal_sub_goal_word_path(goal, sub_goal), class: 'my-btn my-btn__small' %>
          <%= link_to "Edit", edit_goal_sub_goal_path(goal, sub_goal), class: 'my-btn my-btn__small' %>
          <%= button_to "Delete", [goal, sub_goal], method: :delete, class: 'my-btn my-btn__small my-btn__delete' %>
        <% else %>
          <% if @patient.sub_goals.exists?(sub_goal.id) %>
            <div class="comment_message">
              <span>Therapist Feedback: </span>
              <%= @patient.comments.find_by(sub_goal_id: sub_goal.id).message %>
            </div>
          <% else %>
            <%= link_to 'Create Note', new_patient_comment_path(@patient, { sub_goal_id: sub_goal.id }), class: 'my-btn my-btn__small' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sub_goals/edit.html.erb
<% @page_title = truncate("Edit | #{@sub_goal.title}", length: 50) %>

<div class="my-form">
  <%= link_to "<< Go Back", goal_path(@goal), class: 'back__link' %>
  <div class="my-form__body">
    <%= render "form", sub_goal: @sub_goal %>
  </div>
</div>

app/views/sub_goals/new.html.erb
<% @page_title = 'Add New Sub-Goal' %>

<div class="my-form">
  <%= link_to "<< Go Back", goal_path(@goal), class: 'back__link' %>
  <div class="my-form__body">
    <%= render "form", sub_goal: @sub_goal %>
  </div>
</div>

app/views/words/_form.html.erb
<%= form_with(model: [@goal, @sub_goal, word]) do |form| %>

  <%=error_messages_for(form.object) %>

  <div class="my-form__info">
    <div>
      <span>Goal:</span>
      <%= @sub_goal.goal.title %>
    </div>
    <div>
      <span>Sub-Goal:</span>
      <%= @sub_goal.title %>
    </div>
  </div>


  <div class="my-form__control">
    <%= form.label :name, 'Name of the word:' %>
    <%= form.text_field :name, placeholder: 'e.g. fish' %>
  </div>

  <div class="my-form__control">
    <%= form.submit class: 'my-form__action-btn' %>
  </div>
<% end %>

app/views/words/_word.html.erb
<div class="d-flex justify-content-between word__tile">
  <div class="word__name"><%= word.name %></div>
  <div class="d-flex word__controls">
    <% if @patient %>
      <% if @patient.words.exists?(word.id) %>
        <div class="word__stats">
          <div class="word__trials">
            <%= @patient.pronunciations.find_by(word_id: word.id).trials %>
          </div>
          <div class="word__prompt">
            <%= prompting_level(@patient, word) %>
          </div>
          <div class="word__score">
            <%= calc_score(@patient, word)[0] %>
          </div>
          <div class="word__percent">
            <%= calc_score(@patient, word)[1] %>%
          </div>
        </div>
      <% else %>
        <div class="word__actions">
          <%= link_to 'Do Trials', new_patient_pronunciation_path(@patient, { word_id: word.id }), class: 'my-btn my-btn__small' %>
        </div>
      <% end %>
    <% else %>
      <div class="word__actions">
        <%= link_to "Edit", edit_goal_sub_goal_word_path(goal, sub_goal, word), class: 'my-btn my-btn__small' %>
        <%= button_to "Delete", [sub_goal.goal, sub_goal, word], method: :delete, class: 'my-btn my-btn__small my-btn__delete ' %>
      </div>
    <% end %>
  </div>
</div>

app/views/words/edit.html.erb
<% @page_title = "Edit | #{@word.name}" %>

<div class="my-form">
  <%= link_to "<< Go Back", goal_path(@goal), class: 'back__link' %>
  <div class="my-form__body">
    <%= render "form", word: @word %>
  </div>
</div>

app/views/words/new.html.erb
<% @page_title = 'Add New Word' %>

<div class="my-form">
  <%= link_to "<< Go Back", goal_path(@goal), class: 'back__link' %>
  <div class="my-form__body">
    <%= render "form", word: @word %>
  </div>
</div>