config/routes.rb
Rails.application.routes.draw do

  resources :patients, only: [:index] do
    resources :plan_of_cares, only: [:index, :show, :new, :create]
    resources :comments, only: [:new, :create]
    resources :pronunciations, only: [:new, :create]
  end

  resources :goals do
    resources :sub_goals, except: [:index, :show] do
      resources :words, except: [:index, :show]
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "patients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :patient
  belongs_to :sub_goal
end

app/models/goal.rb
class Goal < ApplicationRecord
  has_many :sub_goals, dependent: :destroy

  has_many :plan_of_cares
  has_many :patients, through: :plan_of_cares

  validates :title, presence: true, uniqueness: true

  scope :alphabetically, -> { order('title') }
  scope :ltg, -> { where(goal_type: 'LTG') }
  scope :stg, -> { where(goal_type: 'STG') }
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :plan_of_cares
  has_many :goals, through: :plan_of_cares

  has_many :comments
  has_many :sub_goals, through: :comments

  has_many :pronunciations
  has_many :words, through: :pronunciations
end

app/models/plan_of_care.rb
class PlanOfCare < ApplicationRecord
  belongs_to :patient
  belongs_to :goal
end

app/models/pronunciation.rb
class Pronunciation < ApplicationRecord
  belongs_to :patient
  belongs_to :word
end

app/models/sub_goal.rb
class SubGoal < ApplicationRecord
  belongs_to :goal
  has_many :words, dependent: :destroy

  has_many :comments
  has_many :patients, through: :comments

  validates :title, presence: true, uniqueness: { scope: :goal_id }
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :sub_goal

  has_many :pronunciations
  has_many :patients, through: :pronunciations

  validates :name, presence: true, uniqueness: { scope: :sub_goal_id }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_patient

  def new
    @sub_goal = SubGoal.find(params[:sub_goal_id])
    @comment = @patient.comments.build
  end

  def create
    @comment = @patient.comments.build(comment_params)

    if @comment.save
      redirect_to patient_plan_of_care_path(@patient, @comment.sub_goal.goal), notice: 'Comment registered'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def find_patient
    @patient = Patient.find(params[:patient_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:patient_id, :sub_goal_id, :message)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: %i[edit update destroy]

  def index
    @goals = Goal.alphabetically
    @ltg_goals = @goals.ltg
    @stg_goals = @goals.stg
  end

  def show
    @goal = Goal.includes(sub_goals: :words).find(params[:id])
  end

  def new
    @goal = Goal.new
  end

  def edit; end

  def create
    @goal = Goal.new(goal_params)

    if @goal.save
      redirect_to goals_path, notice: 'Goal was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @goal.update(goal_params)
      redirect_to goal_path(@goal), notice: "'#{@goal.title}' updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @goal.destroy
    redirect_to goals_path, notice: 'Goal was successfully destroyed.'
  end

  private

  def set_goal
    @goal = Goal.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:title, :goal_type, :more_info)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: %i[edit update destroy]
  before_action :find_goal
  before_action :find_sub_goal

  def new
    @word = @sub_goal.words.build
  end

  def edit; end

  def create
    @word = @sub_goal.words.build(word_params)

    if @word.save
      redirect_to goal_path(@goal), notice: "Word created: #{@word.name}"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @word.update(word_params)
      redirect_to goal_path(@goal), notice: 'Word was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @word.destroy
    redirect_to goal_path(@goal), notice: "'#{@word.name}' deleted"
  end

  private

  def find_goal
    @goal = Goal.find(params[:goal_id])
  end

  def find_sub_goal
    @sub_goal = SubGoal.includes(:words).find(params[:sub_goal_id])
  end

  def set_word
    @word = Word.find(params[:id])
  end

  def word_params
    params.require(:word).permit(:name, :sub_goal_id, :word_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render(partial: 'application/error_messages', locals: { object: object })
  end

  def notification(type, color)
    "<div class='notification-#{color}'>#{type}</div>".html_safe if type.present?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/plan_of_cares_helper.rb
module PlanOfCaresHelper
end

app/helpers/pronunciations_helper.rb
module PronunciationsHelper
end

app/helpers/sub_goals_helper.rb
module SubGoalsHelper
end

app/helpers/words_helper.rb
module WordsHelper
  def calc_score(patient, word)
    trials = patient.pronunciations.find_by(word_id: word.id).trials
    success = trials.count('+')
    total = trials.length
    ["#{success}/#{total}", (success * 100) / total]
  end

  def prompting_level(patient, word)
    level = patient.pronunciations.find_by(word_id: word.id).prompting_level

    case level
    when 'Independent'
      "<div class='independent'>Independent</div>".html_safe
    when 'Intermediate'
      "<div class='intermediate'>Intermediate</div>".html_safe
    else
      "<div class='controlling'>Controlling</div>".html_safe
    end
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark my-navbar-bg fixed-top">
  <div class="container-fluid">
    <%= link_to 'visit notes', patients_path, class: 'navbar-brand' %>
    <div class="navbar-brand"><%= @page_title || 'No Title' %></div>
    <ul class="navbar-nav fw-bold">
      <li class="nav-item">
        <%= link_to 'Patients', patients_path, class: 'nav-link active' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Goals', goals_path, class: 'nav-link active' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<div class="notification">
  <%= notification notice, 'green' %>
  <%= notification alert, 'red' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VisitNotes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous" defer></script>
  </head>

  <body>

  <%= render 'layouts/header' %>

  <div class="my-container">
    <%= yield %>
  </div>


  </body>
</html>